AWSTemplateFormatVersion: "2010-09-09"
Description: ---

Parameters:
  GroupName:
    Type: String
  ServiceName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:

  WebBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${GroupName}-${Environment}-web'

  ModuleBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${GroupName}-${Environment}-mdl'
#
#  WebBucketPolicy:
#    Type: AWS::S3::BucketPolicy
#    Properties:
#      Bucket: !Ref WebBucket
#      PolicyDocument:
#        Statement:
#          - Action: s3:GetObject
#            Effect: Allow
#            Resource: !Sub 'arn:aws:s3:::${WebBucket}/*'
#            Principal:
#              AWS: !Sub

Outputs:
  WebBucketName:
    Value: !Ref WebBucket
  ModuleBucketName:
    Value: !Ref ModuleBucket
