name: Cloudformation auto deployment for production

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: tokyo-crafter/aws-stack-cmn/.github/workflows/deploy.yaml@v1
    with:
      environment: prd
