name: Cloudformation auto deployment for develop

on:
  push:
    branches:
      - main # for debug
      - release
      - develop

jobs:
  lint:
    uses: tokyo-crafter/aws-stack-cmn/.github/workflows/linter.yaml@main

  preparation:
    needs:
      - lint
    runs-on: ubuntu-20.04
    outputs:
      environment: ${{ steps.check_environment.outputs.environment }} # stg or dev
    steps:
      - id: check_environment
        name: 'Check environment'
        shell: bash
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ $BRANCH == "release"* ]];  then
            ENVIRONMENT="stg";
          else
            ENVIRONMENT="dev";
          fi
          echo "ENVIRONMENT = ${ENVIRONMENT}"
          echo "::set-output name=environment::$ENVIRONMENT"

  deploy:
    needs:
      - preparation
    uses: tokyo-crafter/aws-stack-cmn/.github/workflows/deploy.yaml@main
    with:
      environment: ${{ needs.preparation.outputs.environment }}
    secrets:
      GROUP_NAME: ${{ secrets.GROUP_NAME }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEPLOYMENT_ROLE_ARN: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
    permissions:
      id-token: write
      contents: read

  create_release:
    needs:
      - preparation
      - deploy
    if: ${{ needs.preparation.outputs.environment }}=='stg'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"

      - name: 'Set change log'
        uses: scottbrenner/generate-changelog-action@master
        id: change-log

      - name: 'Bump version and push tag'
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "minor"

      - name: 'Create release draft'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          draft: true
          body: ${{ steps.change-log.outputs.changelog }}
