name: Cloudformation deployment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_DEPLOYMENT_ROLE_ARN: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          role-to-assume: ${{ env.AWS_DEPLOYMENT_ROLE_ARN }}
          role-session-name: GitHubActions-${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Deploy Cloudformation Stack'
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          GROUP_NAME: ${{ secrets.GROUP_NAME }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          STACK_NAME: ${{ secrets.GROUP_NAME }}-${{ secrets.SERVICE_NAME }}-stack
          TEMPLATE_FILE: cfn/parent.tamplate.yaml
        run: |
          aws cloudformation deploy \
            --stack-name ${STACK_NAME} \
            --template-file ${TEMPLATE_FILE} \
            --parameter-overrides \
                Environment=${ENVIRONMENT} \
                GroupName=${GROUP_NAME} \
                ServiceName=${SERVICE_NAME} \
            --no-fail-on-empty-changeset
